export const MethodIdentifiers = {
    Login: "account/signin",
    AuthenticateUserWithCookie: "auth/cookie/authenticate",
    CreateAccount: "account/signup",
    CreateChannel: "channels/create",
    DestroyChannel: "channels/destroy",
    ShowChannel: "channels/show",
    UpdateStatus: "statuses/update",
    DestroyStatus: "statuses/destroy",
    ShowStatus: "statuses/show",
    CreateLike: "likes/create",
    CreateFavorite: "favorites/create",
    DestroyFavorite: "favorites/destroy",
    ShowUser: "users/show",
    ChannelTimeline: "timeline/channel",
}
